# Generated by scripts/generate-sdks.ts from the v1 OpenAPI document. Do not edit.
from __future__ import annotations

from typing import Any, Literal, NamedTuple, NotRequired, TypedDict


class Operation(NamedTuple):
    method: str
    path: str
    path_params: tuple[str, ...]
    query_params: tuple[str, ...]
    body: bool


class HealthzOutput(TypedDict):
    status: Literal["ok"]


class ReadyzOutput(TypedDict):
    status: Literal["ready"]


class AccessScope(TypedDict):
    workspace_id: str
    principal: Principal
    role: Literal["owner", "admin", "member", "agent", "device"]
    scopes: list[Literal["context:read", "context:write", "recordings:read", "actions:request", "actions:execute", "workspace:admin", "capture:ingest"]]
    meetings: AccessScopeMeetings | AccessScopeMeetings2
    permission_revision: int


class Principal(TypedDict):
    id: str
    kind: Literal["human", "agent", "device"]
    display_name: str


class AccessScopeMeetings(TypedDict):
    kind: Literal["accessible"]


class AccessScopeMeetings2(TypedDict):
    kind: Literal["allowlist"]
    meeting_ids: list[str]


class ListMeetingsInput(TypedDict):
    state: NotRequired[Literal["provisional", "active", "closing", "closed", "interrupted"]]
    cursor: NotRequired[str]
    limit: NotRequired[int]


class ListMeetingsOutput(TypedDict):
    items: list[Meeting]
    next_cursor: str | None


class Meeting(TypedDict):
    id: str
    workspace_id: str
    state: Literal["provisional", "active", "closing", "closed", "interrupted"]
    title: str | None
    started_at: str
    ended_at: str | None
    timezone: str
    boundary_revision: int
    visibility: Literal["restricted", "workspace"]
    processing: MeetingProcessing


class MeetingProcessing(TypedDict):
    transcript: Literal["pending", "partial", "complete", "failed"]
    notes: Literal["pending", "partial", "complete", "failed"]
    memory: Literal["pending", "partial", "complete", "failed"]
    recording: Literal["pending", "partial", "complete", "failed"]


class GetMeetingInput(TypedDict):
    meeting_id: str


class GetTranscriptInput(TypedDict):
    meeting_id: str
    cursor: NotRequired[str]
    limit: NotRequired[int]


class GetTranscriptOutput(TypedDict):
    items: list[TranscriptSegment]
    next_cursor: str | None


class TranscriptSegment(TypedDict):
    id: str
    source: SourceRange
    text: str
    status: Literal["partial", "final"]
    revision: int
    origin: Literal["live", "batch", "correction"]
    provider: str
    model: str
    provider_connection_id: str | None
    speaker_label: str | None
    speaker_track_id: str | None
    confidence: float | None
    created_at: str


class SourceRange(TypedDict):
    epoch_id: str
    track: int
    sample_start: int
    sample_end: int


class RecordingAccessInput(TypedDict):
    meeting_id: str


class RecordingAccess(TypedDict):
    meeting_id: str
    boundary_revision: int
    url: str
    expires_at: str
    gaps: list[SourceRange]


class GetContextInput(TypedDict):
    meeting_id: str


class ContextSnapshot(TypedDict):
    meeting_id: str
    revision: int
    as_of: str
    timezone: str
    source_watermark: ContextSnapshotSourceWatermark | None
    items: list[ContextItem]
    changes_cursor: str
    truncated: bool


class ContextSnapshotSourceWatermark(TypedDict):
    epoch_id: str
    sample_end: int


class ContextItem(TypedDict):
    id: str
    revision: int
    meeting_id: str | None
    kind: Literal["decision", "commitment", "constraint", "project_fact", "preference", "open_question", "research_observation"]
    text: str
    state: Literal["provisional", "committed", "superseded"]
    derivation: Literal["spoken", "inferred", "human_correction", "external"]
    event_at: str | None
    valid_from: str | None
    valid_until: str | None
    time: TimeExpression | None
    author: Author
    sources: list[SegmentSource | ArtifactSource]
    supersedes: ContextItemSupersedes | None
    created_at: str


class TimeExpression(TypedDict):
    phrase: str
    normalized: str | None
    anchor: str
    timezone: str
    ambiguous: bool


class Author(TypedDict):
    type: Literal["human", "agent", "system"]
    id: str


class SegmentSource(TypedDict):
    segment_id: str
    start_ms: int
    end_ms: int


class ArtifactSource(TypedDict):
    artifact_id: str


class ContextItemSupersedes(TypedDict):
    id: str
    revision: int


class SearchContextInput(TypedDict):
    q: str
    meeting_id: NotRequired[str]
    cursor: NotRequired[str]
    limit: NotRequired[int]


class SearchContextOutput(TypedDict):
    items: list[ContextItem]
    next_cursor: str | None


class AddContextItem(TypedDict):
    meeting_id: str | None
    expected_revision: int
    kind: Literal["decision", "commitment", "constraint", "project_fact", "preference", "open_question", "research_observation"]
    text: str
    sources: list[SegmentSource | ArtifactSource]
    idempotency_key: str


class ReviseContextItemInput(TypedDict):
    expected_revision: int
    text: str
    sources: list[SegmentSource | ArtifactSource]
    idempotency_key: str
    item_id: str


class GetContextChangesInput(TypedDict):
    meeting_id: NotRequired[str]
    cursor: NotRequired[str]
    limit: NotRequired[int]


class GetContextChangesOutput(TypedDict):
    items: list[ContextEvent]
    next_cursor: str | None


class ContextEvent(TypedDict):
    seq: int
    meeting_id: str | None
    item: ContextEventItem | None
    change: Literal["item_added", "item_revised", "item_superseded", "meeting_boundary_changed", "access_changed"]
    actor: str
    permission_revision: int
    created_at: str


class ContextEventItem(TypedDict):
    id: str
    revision: int


class GetSourceInput(TypedDict):
    source_id: str


class SourceRecord(TypedDict):
    id: str
    kind: Literal["segment", "artifact"]
    meeting_id: str | None
    text: str
    segment: TranscriptSegment | None


class SearchIntegrationActionsInput(TypedDict):
    intent: str
    app: NotRequired[str]
    limit: NotRequired[int]


class SearchIntegrationActionsOutput(TypedDict):
    matches: list[IntegrationActionMatch]
    refinement_hint: str | None


class IntegrationActionMatch(TypedDict):
    action_key: str
    app: str
    purpose: str
    connection: Literal["connected", "not_connected", "not_permitted"]
    effect: Literal["read", "write", "send", "delete"]


class GetIntegrationActionInput(TypedDict):
    account_id: NotRequired[str]
    configuration: NotRequired[dict[str, Any]]
    field: NotRequired[str]
    options_cursor: NotRequired[str]
    action_key: str


class GetIntegrationActionOutput(TypedDict):
    action_key: str
    version: str
    configuration_ref: str
    fields: list[GetIntegrationActionOutputFieldsItem]
    missing: list[str]
    options: GetIntegrationActionOutputOptions | None
    complete: bool


class GetIntegrationActionOutputFieldsItem(TypedDict):
    name: str
    type: str
    required: bool
    description: str | None
    remote_options: bool


class GetIntegrationActionOutputOptions(TypedDict):
    field: str
    values: list[GetIntegrationActionOutputOptionsValuesItem]
    next_cursor: str | None


class GetIntegrationActionOutputOptionsValuesItem(TypedDict):
    label: str
    value: Any


class RequestActionInput(TypedDict):
    action_key: str
    configuration_ref: str
    version: str
    arguments: dict[str, Any]
    meeting_id: str | None
    idempotency_key: str


class RequestActionOutput(TypedDict):
    action_id: str
    state: Literal["proposed", "awaiting_authorization", "queued", "running", "succeeded", "failed", "unknown", "cancelled"]


class GetActionInput(TypedDict):
    action_id: str


class ActionReceipt(TypedDict):
    action_id: str
    action_key: str
    meeting_id: str | None
    state: Literal["proposed", "awaiting_authorization", "queued", "running", "succeeded", "failed", "unknown", "cancelled"]
    args_sha256: str
    grant: ActionReceiptGrant | None
    provider_receipt: dict[str, Any] | None
    attempts: int
    reconciliation: Literal["none", "pending", "reconciled"]
    updated_at: str


class ActionReceiptGrant(TypedDict):
    id: str
    version: int


class ListAgentsInput(TypedDict):
    cursor: NotRequired[str]
    limit: NotRequired[int]


class ListAgentsOutput(TypedDict):
    items: list[AgentCredential]
    next_cursor: str | None


class AgentCredential(TypedDict):
    credential_id: str
    agent_id: str
    display_name: str
    scopes: list[Literal["context:read", "context:write", "recordings:read", "actions:request", "actions:execute", "workspace:admin", "capture:ingest"]]
    meeting_ids: list[str] | None
    created_at: str
    expires_at: str | None
    revoked_at: str | None
    last_used_at: str | None


class CreateAgent(TypedDict):
    display_name: str
    scopes: list[Literal["context:read", "context:write", "recordings:read", "actions:request", "actions:execute", "workspace:admin", "capture:ingest"]]
    meeting_ids: list[str] | None
    expires_at: str | None


class CreateAgentOutput(TypedDict):
    credential: AgentCredential
    token: str


class RevokeCredentialInput(TypedDict):
    agent_id: str
    credential_id: str


# Each entry: input TypedDict -> output TypedDict, then the route.
OPERATIONS: dict[str, Operation] = {
    # dict[str, Any] -> HealthzOutput
    "health.healthz": Operation("GET", "/healthz", (), (), False),
    # dict[str, Any] -> ReadyzOutput
    "health.readyz": Operation("GET", "/readyz", (), (), False),
    # dict[str, Any] -> AccessScope
    "session.getSession": Operation("GET", "/api/v1/session", (), (), False),
    # ListMeetingsInput -> ListMeetingsOutput
    "meetings.listMeetings": Operation("GET", "/api/v1/meetings", (), ("state", "cursor", "limit", ), False),
    # GetMeetingInput -> Meeting
    "meetings.getMeeting": Operation("GET", "/api/v1/meetings/{meeting_id}", ("meeting_id", ), (), False),
    # GetTranscriptInput -> GetTranscriptOutput
    "meetings.getTranscript": Operation("GET", "/api/v1/meetings/{meeting_id}/transcript", ("meeting_id", ), ("cursor", "limit", ), False),
    # RecordingAccessInput -> RecordingAccess
    "meetings.recordingAccess": Operation("POST", "/api/v1/meetings/{meeting_id}/recording-access", ("meeting_id", ), (), False),
    # GetContextInput -> ContextSnapshot
    "context.getContext": Operation("GET", "/api/v1/meetings/{meeting_id}/context", ("meeting_id", ), (), False),
    # SearchContextInput -> SearchContextOutput
    "context.searchContext": Operation("GET", "/api/v1/context/search", (), ("q", "meeting_id", "cursor", "limit", ), False),
    # AddContextItem -> ContextItem
    "context.addContextItem": Operation("POST", "/api/v1/context/items", (), (), True),
    # ReviseContextItemInput -> ContextItem
    "context.reviseContextItem": Operation("PATCH", "/api/v1/context/items/{item_id}", ("item_id", ), (), True),
    # GetContextChangesInput -> GetContextChangesOutput
    "context.getContextChanges": Operation("GET", "/api/v1/context/changes", (), ("meeting_id", "cursor", "limit", ), False),
    # GetSourceInput -> SourceRecord
    "context.getSource": Operation("GET", "/api/v1/sources/{source_id}", ("source_id", ), (), False),
    # SearchIntegrationActionsInput -> SearchIntegrationActionsOutput
    "integrations.searchIntegrationActions": Operation("GET", "/api/v1/integrations/actions", (), ("intent", "app", "limit", ), False),
    # GetIntegrationActionInput -> GetIntegrationActionOutput
    "integrations.getIntegrationAction": Operation("POST", "/api/v1/integrations/actions/{action_key}/schema", ("action_key", ), (), True),
    # RequestActionInput -> RequestActionOutput
    "actions.requestAction": Operation("POST", "/api/v1/actions", (), (), True),
    # GetActionInput -> ActionReceipt
    "actions.getAction": Operation("GET", "/api/v1/actions/{action_id}", ("action_id", ), (), False),
    # ListAgentsInput -> ListAgentsOutput
    "agents.listAgents": Operation("GET", "/api/v1/agents", (), ("cursor", "limit", ), False),
    # CreateAgent -> CreateAgentOutput
    "agents.createAgent": Operation("POST", "/api/v1/agents", (), (), True),
    # RevokeCredentialInput -> AgentCredential
    "agents.revokeCredential": Operation("DELETE", "/api/v1/agents/{agent_id}/credentials/{credential_id}", ("agent_id", "credential_id", ), (), False),
}
