# Generated by scripts/generate-sdks.ts from the v1 OpenAPI document. Do not edit.
from __future__ import annotations

from typing import Any, Literal, NamedTuple, NotRequired, TypedDict


class Operation(NamedTuple):
    method: str
    path: str
    path_params: tuple[str, ...]
    query_params: tuple[str, ...]
    body: bool


class HealthzOutput(TypedDict):
    status: Literal["ok"]


class ReadyzOutput(TypedDict):
    status: Literal["ready"]


class AccessScope(TypedDict):
    workspace_id: str
    principal: Principal
    role: Literal["owner", "admin", "member", "agent", "device"]
    scopes: list[Literal["context:read", "context:write", "recordings:read", "actions:request", "actions:execute", "workspace:admin", "capture:ingest"]]
    meetings: AccessScopeMeetings | AccessScopeMeetings2
    permission_revision: int


class Principal(TypedDict):
    id: str
    kind: Literal["human", "agent", "device"]
    display_name: str


class AccessScopeMeetings(TypedDict):
    kind: Literal["accessible"]


class AccessScopeMeetings2(TypedDict):
    kind: Literal["allowlist"]
    meeting_ids: list[str]


class RegisterListener(TypedDict):
    name: str
    mode: Literal["room", "laptop"]
    capabilities: dict[str, Any]


class Listener(TypedDict):
    id: str
    workspace_id: str
    name: str
    mode: Literal["room", "laptop"]
    state: Literal["stopped", "starting", "listening", "reconnecting", "paused", "degraded"]
    lease_generation: int
    lease_expires_at: str | None
    current_epoch_id: str | None
    last_heartbeat_at: str | None


class HeartbeatInput(TypedDict):
    lease_generation: int
    state: Literal["stopped", "starting", "listening", "reconnecting", "paused", "degraded"]
    epoch_id: str | None
    buffered_chunks: int
    storage_bytes_free: float | None
    listener_id: str


class HeartbeatReceipt(TypedDict):
    lease_generation: int
    lease_expires_at: str
    owner: bool


ListMeetingsInput = TypedDict("ListMeetingsInput", {
    "state": "NotRequired[Literal[\"provisional\", \"active\", \"closing\", \"closed\", \"interrupted\"]]",
    "from": "NotRequired[str]",
    "to": "NotRequired[str]",
    "listener": "NotRequired[str]",
    "participant": "NotRequired[str]",
    "cursor": "NotRequired[str]",
    "limit": "NotRequired[int]",
})


class MeetingPage(TypedDict):
    meetings: list[Meeting]
    next_cursor: str | None


class Meeting(TypedDict):
    id: str
    workspace_id: str
    state: Literal["provisional", "active", "closing", "closed", "interrupted"]
    title: str | None
    started_at: str
    ended_at: str | None
    timezone: str
    boundary_revision: int
    visibility: Literal["restricted", "workspace"]
    processing: MeetingProcessing


class MeetingProcessing(TypedDict):
    transcript: Literal["pending", "partial", "complete", "failed"]
    notes: Literal["pending", "partial", "complete", "failed"]
    memory: Literal["pending", "partial", "complete", "failed"]
    recording: Literal["pending", "partial", "complete", "failed"]


class MergeMeetings(TypedDict):
    target: MergeMeetingsTarget
    source: MergeMeetingsSource


class MergeMeetingsTarget(TypedDict):
    meeting_id: str
    expected_revision: int


class MergeMeetingsSource(TypedDict):
    meeting_id: str
    expected_revision: int


class GetMeetingInput(TypedDict):
    meeting_id: str


class CloseMeetingInput(TypedDict):
    meeting_id: str


class SplitMeetingInput(TypedDict):
    expected_revision: int
    at: EndMeeting
    meeting_id: str


class EndMeeting(TypedDict):
    epoch_id: str
    sample: int


class SplitResult(TypedDict):
    earlier: Meeting
    later: Meeting


class GetTranscriptInput(TypedDict):
    meeting_id: str
    cursor: NotRequired[str]
    limit: NotRequired[int]


class TranscriptPage(TypedDict):
    meeting_id: str
    boundary_revision: int
    segments: list[TranscriptSegment]
    speakers: list[SpeakerTrack]
    next_cursor: str | None


class TranscriptSegment(TypedDict):
    id: str
    source: SourceRange
    text: str
    status: Literal["partial", "final"]
    revision: int
    origin: Literal["live", "batch", "correction"]
    provider: str
    model: str
    provider_connection_id: str | None
    speaker_label: str | None
    speaker_track_id: str | None
    confidence: float | None
    created_at: str


class SourceRange(TypedDict):
    epoch_id: str
    track: int
    sample_start: int
    sample_end: int


class SpeakerTrack(TypedDict):
    id: str
    epoch_id: str
    track: int
    provider: str
    provider_label: str
    sample_start: int
    sample_end: int
    profile_id: str | None
    mapping_source: Literal["enrollment", "user_confirmed"] | None
    attribution_revision: int
    confidence: float | None


class RecordingAccessInput(TypedDict):
    meeting_id: str


class RecordingAccess(TypedDict):
    meeting_id: str
    boundary_revision: int
    url: str
    expires_at: str
    gaps: list[SourceRange]
    pieces: list[SourceRange]
    sample_rate: Literal[8000, 16000, 22050, 24000, 32000, 44100, 48000, 96000]


class GetNotesInput(TypedDict):
    meeting_id: str


class MeetingNotes(TypedDict):
    meeting_id: str
    revision: int
    boundary_revision: int
    model: str
    title: str
    summary: str
    sections: list[MeetingNotesSectionsItem]
    generated_at: str


class MeetingNotesSectionsItem(TypedDict):
    heading: str
    points: list[MeetingNotesSectionsItemPointsItem]


class MeetingNotesSectionsItemPointsItem(TypedDict):
    text: str
    sources: list[SegmentSource]


class SegmentSource(TypedDict):
    segment_id: str
    start_ms: int
    end_ms: int


class ExportMeetingInput(TypedDict):
    meeting_id: str


class MeetingExport(TypedDict):
    meeting_id: str
    notes_revision: int
    format: Literal["markdown"]
    filename: str
    content: str


class MapSpeakerInput(TypedDict):
    speaker_track_id: str
    profile_id: str | None
    expected_revision: int
    meeting_id: str


class GetContextInput(TypedDict):
    meeting_id: str


class ContextSnapshot(TypedDict):
    meeting_id: str
    revision: int
    as_of: str
    timezone: str
    source_watermark: ContextSnapshotSourceWatermark | None
    items: list[ContextItem]
    changes_cursor: str
    truncated: bool


class ContextSnapshotSourceWatermark(TypedDict):
    epoch_id: str
    sample_end: int


class ContextItem(TypedDict):
    id: str
    revision: int
    meeting_id: str | None
    kind: Literal["decision", "commitment", "constraint", "project_fact", "preference", "open_question", "research_observation"]
    text: str
    state: Literal["provisional", "committed", "superseded"]
    derivation: Literal["spoken", "inferred", "human_correction", "external"]
    event_at: str | None
    valid_from: str | None
    valid_until: str | None
    time: TimeExpression | None
    author: Author
    sources: list[SegmentSource | ArtifactSource]
    supersedes: ContextItemSupersedes | None
    created_at: str


class TimeExpression(TypedDict):
    phrase: str
    normalized: str | None
    anchor: str
    timezone: str
    ambiguous: bool


class Author(TypedDict):
    type: Literal["human", "agent", "system"]
    id: str


class ArtifactSource(TypedDict):
    artifact_id: str


class ContextItemSupersedes(TypedDict):
    id: str
    revision: int


class SearchContextInput(TypedDict):
    q: str
    meeting_id: NotRequired[str]
    limit: NotRequired[int]


class SearchContextOutput(TypedDict):
    items: list[ContextItem]


class AddContextItem(TypedDict):
    meeting_id: str | None
    expected_revision: int
    kind: Literal["decision", "commitment", "constraint", "project_fact", "preference", "open_question", "research_observation"]
    text: str
    sources: list[SegmentSource | ArtifactSource]
    idempotency_key: str


class ReviseContextItemInput(TypedDict):
    expected_revision: int
    idempotency_key: str
    kind: NotRequired[Literal["decision", "commitment", "constraint", "project_fact", "preference", "open_question", "research_observation"]]
    text: NotRequired[str]
    sources: NotRequired[list[SegmentSource | ArtifactSource]]
    state: NotRequired[Literal["committed", "superseded"]]
    item_id: str


class GetContextChangesInput(TypedDict):
    cursor: NotRequired[str]
    meeting_id: NotRequired[str]
    limit: NotRequired[int]


class ContextChanges(TypedDict):
    events: list[ContextEvent]
    next_cursor: str


class ContextEvent(TypedDict):
    seq: int
    meeting_id: str | None
    item: ContextEventItem | None
    change: Literal["item_added", "item_revised", "item_superseded", "meeting_boundary_changed", "access_changed"]
    actor: str
    permission_revision: int
    created_at: str


class ContextEventItem(TypedDict):
    id: str
    revision: int


class GetSourceInput(TypedDict):
    source_id: str


class GetSourceOutput(TypedDict):
    kind: Literal["segment"]
    id: str
    meeting_id: str
    text: str
    revision: int
    speaker_label: str | None
    source: SourceRange
    event_at: str
    start_ms: float
    end_ms: float


class GetSourceOutput2(TypedDict):
    kind: Literal["artifact"]
    id: str
    meeting_id: str | None
    title: str
    content_type: str
    content: str | None
    sha256: str
    created_at: str


class SearchIntegrationActionsInput(TypedDict):
    intent: str
    app: NotRequired[str]
    limit: NotRequired[int]


class SearchIntegrationActionsOutput(TypedDict):
    matches: list[IntegrationActionMatch]
    refinement_hint: str | None


class IntegrationActionMatch(TypedDict):
    action_key: str
    app: str
    purpose: str
    connection: Literal["connected", "not_connected", "not_permitted"]
    effect: Literal["read", "write", "send", "delete"]


class GetIntegrationActionInput(TypedDict):
    account_id: NotRequired[str]
    configuration: NotRequired[dict[str, Any]]
    field: NotRequired[str]
    options_cursor: NotRequired[str]
    action_key: str


class GetIntegrationActionOutput(TypedDict):
    action_key: str
    version: str
    configuration_ref: str
    fields: list[GetIntegrationActionOutputFieldsItem]
    missing: list[str]
    options: GetIntegrationActionOutputOptions | None
    complete: bool


class GetIntegrationActionOutputFieldsItem(TypedDict):
    name: str
    type: str
    required: bool
    description: str | None
    remote_options: bool


class GetIntegrationActionOutputOptions(TypedDict):
    field: str
    values: list[GetIntegrationActionOutputOptionsValuesItem]
    next_cursor: str | None


class GetIntegrationActionOutputOptionsValuesItem(TypedDict):
    label: str
    value: Any


class RequestActionInput(TypedDict):
    action_key: str
    configuration_ref: str
    version: str
    arguments: dict[str, Any]
    meeting_id: str | None
    idempotency_key: str
    title: NotRequired[str]


class RequestActionOutput(TypedDict):
    action_id: str
    state: Literal["proposed", "awaiting_authorization", "queued", "running", "succeeded", "failed", "unknown", "cancelled"]


class GetActionInput(TypedDict):
    action_id: str


class ActionReceipt(TypedDict):
    action_id: str
    action_key: str
    meeting_id: str | None
    state: Literal["proposed", "awaiting_authorization", "queued", "running", "succeeded", "failed", "unknown", "cancelled"]
    args_sha256: str
    grant: ActionReceiptGrant | None
    provider_receipt: dict[str, Any] | None
    attempts: int
    reconciliation: Literal["none", "pending", "reconciled", "resolved_by_human"]
    resolved_by: str | None
    resolved_at: str | None
    updated_at: str


class ActionReceiptGrant(TypedDict):
    id: str
    version: int


class ListMeetingActionsInput(TypedDict):
    meeting_id: str
    cursor: NotRequired[str]
    limit: NotRequired[int]


class ActionPage(TypedDict):
    actions: list[ActionReceipt]
    next_cursor: str | None


class ResolveActionInput(TypedDict):
    outcome: Literal["succeeded", "failed"]
    provider_receipt: dict[str, Any] | None
    action_id: str


class CreateActionGrantInput(TypedDict):
    grantee: str
    action_key: str
    account_id: str
    meeting_id: str | None
    restrictions: dict[str, Any]
    expires_at: str | None


class ActionGrant(TypedDict):
    id: str
    owner: str
    grantee: str
    action_key: str
    app: str
    account_id: str
    meeting_id: str | None
    restrictions: dict[str, Any]
    expires_at: str | None
    revoked_at: str | None
    version: int


class RevokeActionGrantInput(TypedDict):
    grant_id: str


class RankMatchesInput(TypedDict):
    profile_id: str
    kind: Literal["needs", "offers"]
    top_k: NotRequired[int]


class ProfileMatches(TypedDict):
    profile_id: str
    kind: Literal["needs", "offers"]
    matches: list[ProfileMatch]


class ProfileMatch(TypedDict):
    profile_id: str
    score: float


class CreateAgent(TypedDict):
    display_name: str
    scopes: list[Literal["context:read", "context:write", "recordings:read", "actions:request", "actions:execute", "workspace:admin", "capture:ingest"]]
    meetings: CreateAgentMeetings | CreateAgentMeetings2
    expires_at: str | None


class CreateAgentMeetings(TypedDict):
    kind: Literal["accessible"]


class CreateAgentMeetings2(TypedDict):
    kind: Literal["allowlist"]
    meeting_ids: list[str]


class CreatedAgent(TypedDict):
    agent: Principal
    credential: AgentCredential
    token: str


class AgentCredential(TypedDict):
    id: str
    scopes: list[Literal["context:read", "context:write", "recordings:read", "actions:request", "actions:execute", "workspace:admin", "capture:ingest"]]
    meetings: AgentCredentialMeetings | AgentCredentialMeetings2
    expires_at: str | None
    revoked_at: str | None
    last_used_at: str | None
    created_at: str


class AgentCredentialMeetings(TypedDict):
    kind: Literal["accessible"]


class AgentCredentialMeetings2(TypedDict):
    kind: Literal["allowlist"]
    meeting_ids: list[str]


class ListAgentsInput(TypedDict):
    cursor: NotRequired[str]
    limit: NotRequired[int]


class AgentPage(TypedDict):
    items: list[AgentWithCredential]
    next_cursor: str | None


class AgentWithCredential(TypedDict):
    agent: Principal
    credential: AgentCredential


class RevokeCredentialInput(TypedDict):
    agent_id: str
    key_id: str


class Workspace(TypedDict):
    id: str
    name: str
    deleted_at: str | None
    purge_after: str | None


class DeleteWorkspace(TypedDict):
    confirm_name: str


# Each entry: input TypedDict -> output TypedDict, then the route.
OPERATIONS: dict[str, Operation] = {
    # dict[str, Any] -> HealthzOutput
    "health.healthz": Operation("GET", "/healthz", (), (), False),
    # dict[str, Any] -> ReadyzOutput
    "health.readyz": Operation("GET", "/readyz", (), (), False),
    # dict[str, Any] -> AccessScope
    "session.getSession": Operation("GET", "/api/v1/session", (), (), False),
    # RegisterListener -> Listener
    "listeners.registerListener": Operation("POST", "/api/v1/listeners", (), (), True),
    # HeartbeatInput -> HeartbeatReceipt
    "listeners.heartbeat": Operation("POST", "/api/v1/listeners/{listener_id}/heartbeat", ("listener_id", ), (), True),
    # ListMeetingsInput -> MeetingPage
    "meetings.listMeetings": Operation("GET", "/api/v1/meetings", (), ("state", "from", "to", "listener", "participant", "cursor", "limit", ), False),
    # MergeMeetings -> Meeting
    "meetings.mergeMeetings": Operation("POST", "/api/v1/meetings/merge", (), (), True),
    # GetMeetingInput -> Meeting
    "meetings.getMeeting": Operation("GET", "/api/v1/meetings/{meeting_id}", ("meeting_id", ), (), False),
    # CloseMeetingInput -> Meeting
    "meetings.closeMeeting": Operation("POST", "/api/v1/meetings/{meeting_id}/close", ("meeting_id", ), (), False),
    # SplitMeetingInput -> SplitResult
    "meetings.splitMeeting": Operation("POST", "/api/v1/meetings/{meeting_id}/split", ("meeting_id", ), (), True),
    # GetTranscriptInput -> TranscriptPage
    "meetings.getTranscript": Operation("GET", "/api/v1/meetings/{meeting_id}/transcript", ("meeting_id", ), ("cursor", "limit", ), False),
    # RecordingAccessInput -> RecordingAccess
    "meetings.recordingAccess": Operation("POST", "/api/v1/meetings/{meeting_id}/recording-access", ("meeting_id", ), (), False),
    # GetNotesInput -> MeetingNotes
    "meetings.getNotes": Operation("GET", "/api/v1/meetings/{meeting_id}/notes", ("meeting_id", ), (), False),
    # ExportMeetingInput -> MeetingExport
    "meetings.exportMeeting": Operation("GET", "/api/v1/meetings/{meeting_id}/export", ("meeting_id", ), (), False),
    # MapSpeakerInput -> list[SpeakerTrack]
    "meetings.mapSpeaker": Operation("POST", "/api/v1/meetings/{meeting_id}/speakers/map", ("meeting_id", ), (), True),
    # GetContextInput -> ContextSnapshot
    "context.getContext": Operation("GET", "/api/v1/meetings/{meeting_id}/context", ("meeting_id", ), (), False),
    # SearchContextInput -> SearchContextOutput
    "context.searchContext": Operation("GET", "/api/v1/context/search", (), ("q", "meeting_id", "limit", ), False),
    # AddContextItem -> ContextItem
    "context.addContextItem": Operation("POST", "/api/v1/context/items", (), (), True),
    # ReviseContextItemInput -> ContextItem
    "context.reviseContextItem": Operation("PATCH", "/api/v1/context/items/{item_id}", ("item_id", ), (), True),
    # GetContextChangesInput -> ContextChanges
    "context.getContextChanges": Operation("GET", "/api/v1/context/changes", (), ("cursor", "meeting_id", "limit", ), False),
    # GetSourceInput -> GetSourceOutput | GetSourceOutput2
    "context.getSource": Operation("GET", "/api/v1/sources/{source_id}", ("source_id", ), (), False),
    # SearchIntegrationActionsInput -> SearchIntegrationActionsOutput
    "integrations.searchIntegrationActions": Operation("GET", "/api/v1/integrations/actions", (), ("intent", "app", "limit", ), False),
    # GetIntegrationActionInput -> GetIntegrationActionOutput
    "integrations.getIntegrationAction": Operation("POST", "/api/v1/integrations/actions/{action_key}/schema", ("action_key", ), (), True),
    # RequestActionInput -> RequestActionOutput
    "actions.requestAction": Operation("POST", "/api/v1/actions", (), (), True),
    # GetActionInput -> ActionReceipt
    "actions.getAction": Operation("GET", "/api/v1/actions/{action_id}", ("action_id", ), (), False),
    # ListMeetingActionsInput -> ActionPage
    "actions.listMeetingActions": Operation("GET", "/api/v1/meetings/{meeting_id}/actions", ("meeting_id", ), ("cursor", "limit", ), False),
    # ResolveActionInput -> ActionReceipt
    "actions.resolveAction": Operation("POST", "/api/v1/actions/{action_id}/resolve", ("action_id", ), (), True),
    # CreateActionGrantInput -> ActionGrant
    "actions.createActionGrant": Operation("POST", "/api/v1/action-grants", (), (), True),
    # RevokeActionGrantInput -> ActionGrant
    "actions.revokeActionGrant": Operation("DELETE", "/api/v1/action-grants/{grant_id}", ("grant_id", ), (), False),
    # RankMatchesInput -> ProfileMatches
    "matching.rankMatches": Operation("GET", "/api/v1/profiles/{profile_id}/matches", ("profile_id", ), ("kind", "top_k", ), False),
    # CreateAgent -> CreatedAgent
    "agents.createAgent": Operation("POST", "/api/v1/agents", (), (), True),
    # ListAgentsInput -> AgentPage
    "agents.listAgents": Operation("GET", "/api/v1/agents", (), ("cursor", "limit", ), False),
    # RevokeCredentialInput -> None
    "agents.revokeCredential": Operation("DELETE", "/api/v1/agents/{agent_id}/credentials/{key_id}", ("agent_id", "key_id", ), (), False),
    # dict[str, Any] -> Workspace
    "workspace.getWorkspace": Operation("GET", "/api/v1/workspace", (), (), False),
    # DeleteWorkspace -> Workspace
    "workspace.deleteWorkspace": Operation("DELETE", "/api/v1/workspace", (), (), True),
    # dict[str, Any] -> Workspace
    "workspace.restoreWorkspace": Operation("POST", "/api/v1/workspace/restore", (), (), False),
}
