// Generated by scripts/generate-sdks.ts from the v1 OpenAPI document. Do not edit.
export interface OperationSpec {
  readonly method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  readonly path: string;
  readonly pathParams: ReadonlyArray<string>;
  readonly queryParams: ReadonlyArray<string>;
  readonly body: boolean;
}

export type HealthzOutput = {
  readonly status: "ok";
};

export type ReadyzOutput = {
  readonly status: "ready";
};

export type AccessScope = {
  readonly workspace_id: string;
  readonly principal: Principal;
  readonly role: "owner" | "admin" | "member" | "agent" | "device";
  readonly scopes: ReadonlyArray<"context:read" | "context:write" | "recordings:read" | "actions:request" | "actions:execute" | "workspace:admin" | "capture:ingest">;
  readonly meetings: AccessScopeMeetings | AccessScopeMeetings2;
  readonly permission_revision: number;
};

export type Principal = {
  readonly id: string;
  readonly kind: "human" | "agent" | "device";
  readonly display_name: string;
};

export type AccessScopeMeetings = {
  readonly kind: "accessible";
};

export type AccessScopeMeetings2 = {
  readonly kind: "allowlist";
  readonly meeting_ids: ReadonlyArray<string>;
};

export type RegisterListener = {
  readonly name: string;
  readonly mode: "room" | "laptop";
  readonly capabilities: Readonly<Record<string, unknown>>;
};

export type Listener = {
  readonly id: string;
  readonly workspace_id: string;
  readonly name: string;
  readonly mode: "room" | "laptop";
  readonly state: "stopped" | "starting" | "listening" | "reconnecting" | "paused" | "degraded";
  readonly lease_generation: number;
  readonly lease_expires_at: string | null;
  readonly current_epoch_id: string | null;
  readonly last_heartbeat_at: string | null;
};

export type HeartbeatInput = {
  readonly lease_generation: number;
  readonly state: "stopped" | "starting" | "listening" | "reconnecting" | "paused" | "degraded";
  readonly epoch_id: string | null;
  readonly buffered_chunks: number;
  readonly storage_bytes_free: number | null;
  readonly listener_id: string;
};

export type HeartbeatReceipt = {
  readonly lease_generation: number;
  readonly lease_expires_at: string;
  readonly owner: boolean;
};

export type ListMeetingsInput = {
  readonly state?: "provisional" | "active" | "closing" | "closed" | "interrupted";
  readonly from?: string;
  readonly to?: string;
  readonly participant?: string;
  readonly cursor?: string;
  readonly limit?: number;
};

export type MeetingPage = {
  readonly meetings: ReadonlyArray<Meeting>;
  readonly next_cursor: string | null;
};

export type Meeting = {
  readonly id: string;
  readonly workspace_id: string;
  readonly state: "provisional" | "active" | "closing" | "closed" | "interrupted";
  readonly title: string | null;
  readonly started_at: string;
  readonly ended_at: string | null;
  readonly timezone: string;
  readonly boundary_revision: number;
  readonly visibility: "restricted" | "workspace";
  readonly processing: MeetingProcessing;
};

export type MeetingProcessing = {
  readonly transcript: "pending" | "partial" | "complete" | "failed";
  readonly notes: "pending" | "partial" | "complete" | "failed";
  readonly memory: "pending" | "partial" | "complete" | "failed";
  readonly recording: "pending" | "partial" | "complete" | "failed";
};

export type MergeMeetings = {
  readonly target: MergeMeetingsTarget;
  readonly source: MergeMeetingsSource;
};

export type MergeMeetingsTarget = {
  readonly meeting_id: string;
  readonly expected_revision: number;
};

export type MergeMeetingsSource = {
  readonly meeting_id: string;
  readonly expected_revision: number;
};

export type GetMeetingInput = {
  readonly meeting_id: string;
};

export type CloseMeetingInput = {
  readonly meeting_id: string;
};

export type SplitMeetingInput = {
  readonly expected_revision: number;
  readonly at: SplitMeetingInputAt;
  readonly meeting_id: string;
};

export type SplitMeetingInputAt = {
  readonly epoch_id: string;
  readonly sample: number;
};

export type SplitResult = {
  readonly earlier: Meeting;
  readonly later: Meeting;
};

export type GetTranscriptInput = {
  readonly meeting_id: string;
  readonly cursor?: string;
  readonly limit?: number;
};

export type TranscriptPage = {
  readonly meeting_id: string;
  readonly boundary_revision: number;
  readonly segments: ReadonlyArray<TranscriptSegment>;
  readonly speakers: ReadonlyArray<SpeakerTrack>;
  readonly next_cursor: string | null;
};

export type TranscriptSegment = {
  readonly id: string;
  readonly source: SourceRange;
  readonly text: string;
  readonly status: "partial" | "final";
  readonly revision: number;
  readonly origin: "live" | "batch" | "correction";
  readonly provider: string;
  readonly model: string;
  readonly provider_connection_id: string | null;
  readonly speaker_label: string | null;
  readonly speaker_track_id: string | null;
  readonly confidence: number | null;
  readonly created_at: string;
};

export type SourceRange = {
  readonly epoch_id: string;
  readonly track: number;
  readonly sample_start: number;
  readonly sample_end: number;
};

export type SpeakerTrack = {
  readonly id: string;
  readonly epoch_id: string;
  readonly track: number;
  readonly provider: string;
  readonly provider_label: string;
  readonly sample_start: number;
  readonly sample_end: number;
  readonly profile_id: string | null;
  readonly mapping_source: "enrollment" | "user_confirmed" | null;
  readonly attribution_revision: number;
  readonly confidence: number | null;
};

export type RecordingAccessInput = {
  readonly meeting_id: string;
};

export type RecordingAccess = {
  readonly meeting_id: string;
  readonly boundary_revision: number;
  readonly url: string;
  readonly expires_at: string;
  readonly gaps: ReadonlyArray<SourceRange>;
  readonly pieces: ReadonlyArray<SourceRange>;
  readonly sample_rate: 8000 | 16000 | 22050 | 24000 | 32000 | 44100 | 48000 | 96000;
};

export type GetNotesInput = {
  readonly meeting_id: string;
};

export type MeetingNotes = {
  readonly meeting_id: string;
  readonly revision: number;
  readonly boundary_revision: number;
  readonly model: string;
  readonly title: string;
  readonly summary: string;
  readonly sections: ReadonlyArray<MeetingNotesSectionsItem>;
  readonly generated_at: string;
};

export type MeetingNotesSectionsItem = {
  readonly heading: string;
  readonly points: ReadonlyArray<MeetingNotesSectionsItemPointsItem>;
};

export type MeetingNotesSectionsItemPointsItem = {
  readonly text: string;
  readonly sources: ReadonlyArray<SegmentSource>;
};

export type SegmentSource = {
  readonly segment_id: string;
  readonly start_ms: number;
  readonly end_ms: number;
};

export type ExportMeetingInput = {
  readonly meeting_id: string;
};

export type MeetingExport = {
  readonly meeting_id: string;
  readonly notes_revision: number;
  readonly format: "markdown";
  readonly filename: string;
  readonly content: string;
};

export type MapSpeakerInput = {
  readonly speaker_track_id: string;
  readonly profile_id: string | null;
  readonly expected_revision: number;
  readonly meeting_id: string;
};

export type GetContextInput = {
  readonly meeting_id: string;
};

export type ContextSnapshot = {
  readonly meeting_id: string;
  readonly revision: number;
  readonly as_of: string;
  readonly timezone: string;
  readonly source_watermark: ContextSnapshotSourceWatermark | null;
  readonly items: ReadonlyArray<ContextItem>;
  readonly changes_cursor: string;
  readonly truncated: boolean;
};

export type ContextSnapshotSourceWatermark = {
  readonly epoch_id: string;
  readonly sample_end: number;
};

export type ContextItem = {
  readonly id: string;
  readonly revision: number;
  readonly meeting_id: string | null;
  readonly kind: "decision" | "commitment" | "constraint" | "project_fact" | "preference" | "open_question" | "research_observation";
  readonly text: string;
  readonly state: "provisional" | "committed" | "superseded";
  readonly derivation: "spoken" | "inferred" | "human_correction" | "external";
  readonly event_at: string | null;
  readonly valid_from: string | null;
  readonly valid_until: string | null;
  readonly time: TimeExpression | null;
  readonly author: Author;
  readonly sources: ReadonlyArray<SegmentSource | ArtifactSource>;
  readonly supersedes: ContextItemSupersedes | null;
  readonly created_at: string;
};

export type TimeExpression = {
  readonly phrase: string;
  readonly normalized: string | null;
  readonly anchor: string;
  readonly timezone: string;
  readonly ambiguous: boolean;
};

export type Author = {
  readonly type: "human" | "agent" | "system";
  readonly id: string;
};

export type ArtifactSource = {
  readonly artifact_id: string;
};

export type ContextItemSupersedes = {
  readonly id: string;
  readonly revision: number;
};

export type SearchContextInput = {
  readonly q: string;
  readonly meeting_id?: string;
  readonly limit?: number;
};

export type SearchContextOutput = {
  readonly items: ReadonlyArray<ContextItem>;
};

export type AddContextItem = {
  readonly meeting_id: string | null;
  readonly expected_revision: number;
  readonly kind: "decision" | "commitment" | "constraint" | "project_fact" | "preference" | "open_question" | "research_observation";
  readonly text: string;
  readonly sources: ReadonlyArray<SegmentSource | ArtifactSource>;
  readonly idempotency_key: string;
};

export type ReviseContextItemInput = {
  readonly expected_revision: number;
  readonly idempotency_key: string;
  readonly kind?: "decision" | "commitment" | "constraint" | "project_fact" | "preference" | "open_question" | "research_observation";
  readonly text?: string;
  readonly sources?: ReadonlyArray<SegmentSource | ArtifactSource>;
  readonly state?: "committed" | "superseded";
  readonly item_id: string;
};

export type GetContextChangesInput = {
  readonly cursor?: string;
  readonly meeting_id?: string;
  readonly limit?: number;
};

export type ContextChanges = {
  readonly events: ReadonlyArray<ContextEvent>;
  readonly next_cursor: string;
};

export type ContextEvent = {
  readonly seq: number;
  readonly meeting_id: string | null;
  readonly item: ContextEventItem | null;
  readonly change: "item_added" | "item_revised" | "item_superseded" | "meeting_boundary_changed" | "access_changed";
  readonly actor: string;
  readonly permission_revision: number;
  readonly created_at: string;
};

export type ContextEventItem = {
  readonly id: string;
  readonly revision: number;
};

export type GetSourceInput = {
  readonly source_id: string;
};

export type GetSourceOutput = {
  readonly kind: "segment";
  readonly id: string;
  readonly meeting_id: string;
  readonly text: string;
  readonly revision: number;
  readonly speaker_label: string | null;
  readonly source: SourceRange;
  readonly event_at: string;
  readonly start_ms: number;
  readonly end_ms: number;
};

export type GetSourceOutput2 = {
  readonly kind: "artifact";
  readonly id: string;
  readonly meeting_id: string | null;
  readonly title: string;
  readonly content_type: string;
  readonly content: string | null;
  readonly sha256: string;
  readonly created_at: string;
};

export type SearchIntegrationActionsInput = {
  readonly intent: string;
  readonly app?: string;
  readonly limit?: number;
};

export type SearchIntegrationActionsOutput = {
  readonly matches: ReadonlyArray<IntegrationActionMatch>;
  readonly refinement_hint: string | null;
};

export type IntegrationActionMatch = {
  readonly action_key: string;
  readonly app: string;
  readonly purpose: string;
  readonly connection: "connected" | "not_connected" | "not_permitted";
  readonly effect: "read" | "write" | "send" | "delete";
};

export type GetIntegrationActionInput = {
  readonly account_id?: string;
  readonly configuration?: Readonly<Record<string, unknown>>;
  readonly field?: string;
  readonly options_cursor?: string;
  readonly action_key: string;
};

export type GetIntegrationActionOutput = {
  readonly action_key: string;
  readonly version: string;
  readonly configuration_ref: string;
  readonly fields: ReadonlyArray<GetIntegrationActionOutputFieldsItem>;
  readonly missing: ReadonlyArray<string>;
  readonly options: GetIntegrationActionOutputOptions | null;
  readonly complete: boolean;
};

export type GetIntegrationActionOutputFieldsItem = {
  readonly name: string;
  readonly type: string;
  readonly required: boolean;
  readonly description: string | null;
  readonly remote_options: boolean;
};

export type GetIntegrationActionOutputOptions = {
  readonly field: string;
  readonly values: ReadonlyArray<GetIntegrationActionOutputOptionsValuesItem>;
  readonly next_cursor: string | null;
};

export type GetIntegrationActionOutputOptionsValuesItem = {
  readonly label: string;
  readonly value: unknown;
};

export type RequestActionInput = {
  readonly action_key: string;
  readonly configuration_ref: string;
  readonly version: string;
  readonly arguments: Readonly<Record<string, unknown>>;
  readonly meeting_id: string | null;
  readonly idempotency_key: string;
};

export type RequestActionOutput = {
  readonly action_id: string;
  readonly state: "proposed" | "awaiting_authorization" | "queued" | "running" | "succeeded" | "failed" | "unknown" | "cancelled";
};

export type GetActionInput = {
  readonly action_id: string;
};

export type ActionReceipt = {
  readonly action_id: string;
  readonly action_key: string;
  readonly meeting_id: string | null;
  readonly state: "proposed" | "awaiting_authorization" | "queued" | "running" | "succeeded" | "failed" | "unknown" | "cancelled";
  readonly args_sha256: string;
  readonly grant: ActionReceiptGrant | null;
  readonly provider_receipt: Readonly<Record<string, unknown>> | null;
  readonly attempts: number;
  readonly reconciliation: "none" | "pending" | "reconciled" | "resolved_by_human";
  readonly resolved_by: string | null;
  readonly resolved_at: string | null;
  readonly updated_at: string;
};

export type ActionReceiptGrant = {
  readonly id: string;
  readonly version: number;
};

export type ListMeetingActionsInput = {
  readonly meeting_id: string;
  readonly cursor?: string;
  readonly limit?: number;
};

export type ActionPage = {
  readonly actions: ReadonlyArray<ActionReceipt>;
  readonly next_cursor: string | null;
};

export type ResolveActionInput = {
  readonly outcome: "succeeded" | "failed";
  readonly provider_receipt: Readonly<Record<string, unknown>> | null;
  readonly action_id: string;
};

export type CreateActionGrantInput = {
  readonly grantee: string;
  readonly action_key: string;
  readonly account_id: string;
  readonly meeting_id: string | null;
  readonly restrictions: Readonly<Record<string, unknown>>;
  readonly expires_at: string | null;
};

export type ActionGrant = {
  readonly id: string;
  readonly owner: string;
  readonly grantee: string;
  readonly action_key: string;
  readonly app: string;
  readonly account_id: string;
  readonly meeting_id: string | null;
  readonly restrictions: Readonly<Record<string, unknown>>;
  readonly expires_at: string | null;
  readonly revoked_at: string | null;
  readonly version: number;
};

export type RevokeActionGrantInput = {
  readonly grant_id: string;
};

export type RankMatchesInput = {
  readonly profile_id: string;
  readonly kind: "needs" | "offers";
  readonly top_k?: number;
};

export type ProfileMatches = {
  readonly profile_id: string;
  readonly kind: "needs" | "offers";
  readonly matches: ReadonlyArray<ProfileMatch>;
};

export type ProfileMatch = {
  readonly profile_id: string;
  readonly score: number;
};

export type CreateAgent = {
  readonly display_name: string;
  readonly scopes: ReadonlyArray<"context:read" | "context:write" | "recordings:read" | "actions:request" | "actions:execute" | "workspace:admin" | "capture:ingest">;
  readonly meetings: CreateAgentMeetings | CreateAgentMeetings2;
  readonly expires_at: string | null;
};

export type CreateAgentMeetings = {
  readonly kind: "accessible";
};

export type CreateAgentMeetings2 = {
  readonly kind: "allowlist";
  readonly meeting_ids: ReadonlyArray<string>;
};

export type CreatedAgent = {
  readonly agent: Principal;
  readonly credential: AgentCredential;
  readonly token: string;
};

export type AgentCredential = {
  readonly id: string;
  readonly scopes: ReadonlyArray<"context:read" | "context:write" | "recordings:read" | "actions:request" | "actions:execute" | "workspace:admin" | "capture:ingest">;
  readonly meetings: AgentCredentialMeetings | AgentCredentialMeetings2;
  readonly expires_at: string | null;
  readonly revoked_at: string | null;
  readonly last_used_at: string | null;
  readonly created_at: string;
};

export type AgentCredentialMeetings = {
  readonly kind: "accessible";
};

export type AgentCredentialMeetings2 = {
  readonly kind: "allowlist";
  readonly meeting_ids: ReadonlyArray<string>;
};

export type ListAgentsInput = {
  readonly cursor?: string;
  readonly limit?: number;
};

export type AgentPage = {
  readonly items: ReadonlyArray<AgentWithCredential>;
  readonly next_cursor: string | null;
};

export type AgentWithCredential = {
  readonly agent: Principal;
  readonly credential: AgentCredential;
};

export type RevokeCredentialInput = {
  readonly agent_id: string;
  readonly key_id: string;
};

export interface Operations {
  'health.healthz': { input: Readonly<Record<string, unknown>>; output: HealthzOutput };
  'health.readyz': { input: Readonly<Record<string, unknown>>; output: ReadyzOutput };
  'session.getSession': { input: Readonly<Record<string, unknown>>; output: AccessScope };
  'listeners.registerListener': { input: RegisterListener; output: Listener };
  'listeners.heartbeat': { input: HeartbeatInput; output: HeartbeatReceipt };
  'meetings.listMeetings': { input: ListMeetingsInput; output: MeetingPage };
  'meetings.mergeMeetings': { input: MergeMeetings; output: Meeting };
  'meetings.getMeeting': { input: GetMeetingInput; output: Meeting };
  'meetings.closeMeeting': { input: CloseMeetingInput; output: Meeting };
  'meetings.splitMeeting': { input: SplitMeetingInput; output: SplitResult };
  'meetings.getTranscript': { input: GetTranscriptInput; output: TranscriptPage };
  'meetings.recordingAccess': { input: RecordingAccessInput; output: RecordingAccess };
  'meetings.getNotes': { input: GetNotesInput; output: MeetingNotes };
  'meetings.exportMeeting': { input: ExportMeetingInput; output: MeetingExport };
  'meetings.mapSpeaker': { input: MapSpeakerInput; output: ReadonlyArray<SpeakerTrack> };
  'context.getContext': { input: GetContextInput; output: ContextSnapshot };
  'context.searchContext': { input: SearchContextInput; output: SearchContextOutput };
  'context.addContextItem': { input: AddContextItem; output: ContextItem };
  'context.reviseContextItem': { input: ReviseContextItemInput; output: ContextItem };
  'context.getContextChanges': { input: GetContextChangesInput; output: ContextChanges };
  'context.getSource': { input: GetSourceInput; output: GetSourceOutput | GetSourceOutput2 };
  'integrations.searchIntegrationActions': { input: SearchIntegrationActionsInput; output: SearchIntegrationActionsOutput };
  'integrations.getIntegrationAction': { input: GetIntegrationActionInput; output: GetIntegrationActionOutput };
  'actions.requestAction': { input: RequestActionInput; output: RequestActionOutput };
  'actions.getAction': { input: GetActionInput; output: ActionReceipt };
  'actions.listMeetingActions': { input: ListMeetingActionsInput; output: ActionPage };
  'actions.resolveAction': { input: ResolveActionInput; output: ActionReceipt };
  'actions.createActionGrant': { input: CreateActionGrantInput; output: ActionGrant };
  'actions.revokeActionGrant': { input: RevokeActionGrantInput; output: ActionGrant };
  'matching.rankMatches': { input: RankMatchesInput; output: ProfileMatches };
  'agents.createAgent': { input: CreateAgent; output: CreatedAgent };
  'agents.listAgents': { input: ListAgentsInput; output: AgentPage };
  'agents.revokeCredential': { input: RevokeCredentialInput; output: null };
}

export const operations: Record<keyof Operations, OperationSpec> = {
  'health.healthz': {"method":"GET","path":"/healthz","pathParams":[],"queryParams":[],"body":false},
  'health.readyz': {"method":"GET","path":"/readyz","pathParams":[],"queryParams":[],"body":false},
  'session.getSession': {"method":"GET","path":"/api/v1/session","pathParams":[],"queryParams":[],"body":false},
  'listeners.registerListener': {"method":"POST","path":"/api/v1/listeners","pathParams":[],"queryParams":[],"body":true},
  'listeners.heartbeat': {"method":"POST","path":"/api/v1/listeners/{listener_id}/heartbeat","pathParams":["listener_id"],"queryParams":[],"body":true},
  'meetings.listMeetings': {"method":"GET","path":"/api/v1/meetings","pathParams":[],"queryParams":["state","from","to","participant","cursor","limit"],"body":false},
  'meetings.mergeMeetings': {"method":"POST","path":"/api/v1/meetings/merge","pathParams":[],"queryParams":[],"body":true},
  'meetings.getMeeting': {"method":"GET","path":"/api/v1/meetings/{meeting_id}","pathParams":["meeting_id"],"queryParams":[],"body":false},
  'meetings.closeMeeting': {"method":"POST","path":"/api/v1/meetings/{meeting_id}/close","pathParams":["meeting_id"],"queryParams":[],"body":false},
  'meetings.splitMeeting': {"method":"POST","path":"/api/v1/meetings/{meeting_id}/split","pathParams":["meeting_id"],"queryParams":[],"body":true},
  'meetings.getTranscript': {"method":"GET","path":"/api/v1/meetings/{meeting_id}/transcript","pathParams":["meeting_id"],"queryParams":["cursor","limit"],"body":false},
  'meetings.recordingAccess': {"method":"POST","path":"/api/v1/meetings/{meeting_id}/recording-access","pathParams":["meeting_id"],"queryParams":[],"body":false},
  'meetings.getNotes': {"method":"GET","path":"/api/v1/meetings/{meeting_id}/notes","pathParams":["meeting_id"],"queryParams":[],"body":false},
  'meetings.exportMeeting': {"method":"GET","path":"/api/v1/meetings/{meeting_id}/export","pathParams":["meeting_id"],"queryParams":[],"body":false},
  'meetings.mapSpeaker': {"method":"POST","path":"/api/v1/meetings/{meeting_id}/speakers/map","pathParams":["meeting_id"],"queryParams":[],"body":true},
  'context.getContext': {"method":"GET","path":"/api/v1/meetings/{meeting_id}/context","pathParams":["meeting_id"],"queryParams":[],"body":false},
  'context.searchContext': {"method":"GET","path":"/api/v1/context/search","pathParams":[],"queryParams":["q","meeting_id","limit"],"body":false},
  'context.addContextItem': {"method":"POST","path":"/api/v1/context/items","pathParams":[],"queryParams":[],"body":true},
  'context.reviseContextItem': {"method":"PATCH","path":"/api/v1/context/items/{item_id}","pathParams":["item_id"],"queryParams":[],"body":true},
  'context.getContextChanges': {"method":"GET","path":"/api/v1/context/changes","pathParams":[],"queryParams":["cursor","meeting_id","limit"],"body":false},
  'context.getSource': {"method":"GET","path":"/api/v1/sources/{source_id}","pathParams":["source_id"],"queryParams":[],"body":false},
  'integrations.searchIntegrationActions': {"method":"GET","path":"/api/v1/integrations/actions","pathParams":[],"queryParams":["intent","app","limit"],"body":false},
  'integrations.getIntegrationAction': {"method":"POST","path":"/api/v1/integrations/actions/{action_key}/schema","pathParams":["action_key"],"queryParams":[],"body":true},
  'actions.requestAction': {"method":"POST","path":"/api/v1/actions","pathParams":[],"queryParams":[],"body":true},
  'actions.getAction': {"method":"GET","path":"/api/v1/actions/{action_id}","pathParams":["action_id"],"queryParams":[],"body":false},
  'actions.listMeetingActions': {"method":"GET","path":"/api/v1/meetings/{meeting_id}/actions","pathParams":["meeting_id"],"queryParams":["cursor","limit"],"body":false},
  'actions.resolveAction': {"method":"POST","path":"/api/v1/actions/{action_id}/resolve","pathParams":["action_id"],"queryParams":[],"body":true},
  'actions.createActionGrant': {"method":"POST","path":"/api/v1/action-grants","pathParams":[],"queryParams":[],"body":true},
  'actions.revokeActionGrant': {"method":"DELETE","path":"/api/v1/action-grants/{grant_id}","pathParams":["grant_id"],"queryParams":[],"body":false},
  'matching.rankMatches': {"method":"GET","path":"/api/v1/profiles/{profile_id}/matches","pathParams":["profile_id"],"queryParams":["kind","top_k"],"body":false},
  'agents.createAgent': {"method":"POST","path":"/api/v1/agents","pathParams":[],"queryParams":[],"body":true},
  'agents.listAgents': {"method":"GET","path":"/api/v1/agents","pathParams":[],"queryParams":["cursor","limit"],"body":false},
  'agents.revokeCredential': {"method":"DELETE","path":"/api/v1/agents/{agent_id}/credentials/{key_id}","pathParams":["agent_id","key_id"],"queryParams":[],"body":false},
};
