// Generated by scripts/generate-sdks.ts from the v1 OpenAPI document. Do not edit.
export interface OperationSpec {
  readonly method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  readonly path: string;
  readonly pathParams: ReadonlyArray<string>;
  readonly queryParams: ReadonlyArray<string>;
  readonly body: boolean;
}

export type HealthzOutput = {
  readonly status: "ok";
};

export type ReadyzOutput = {
  readonly status: "ready";
};

export type AccessScope = {
  readonly workspace_id: string;
  readonly principal: Principal;
  readonly role: "owner" | "admin" | "member" | "agent" | "device";
  readonly scopes: ReadonlyArray<"context:read" | "context:write" | "recordings:read" | "actions:request" | "actions:execute" | "workspace:admin" | "capture:ingest">;
  readonly meetings: AccessScopeMeetings | AccessScopeMeetings2;
  readonly permission_revision: number;
};

export type Principal = {
  readonly id: string;
  readonly kind: "human" | "agent" | "device";
  readonly display_name: string;
};

export type AccessScopeMeetings = {
  readonly kind: "accessible";
};

export type AccessScopeMeetings2 = {
  readonly kind: "allowlist";
  readonly meeting_ids: ReadonlyArray<string>;
};

export type ListMeetingsInput = {
  readonly state?: "provisional" | "active" | "closing" | "closed" | "interrupted";
  readonly cursor?: string;
  readonly limit?: number;
};

export type ListMeetingsOutput = {
  readonly items: ReadonlyArray<Meeting>;
  readonly next_cursor: string | null;
};

export type Meeting = {
  readonly id: string;
  readonly workspace_id: string;
  readonly state: "provisional" | "active" | "closing" | "closed" | "interrupted";
  readonly title: string | null;
  readonly started_at: string;
  readonly ended_at: string | null;
  readonly timezone: string;
  readonly boundary_revision: number;
  readonly visibility: "restricted" | "workspace";
  readonly processing: MeetingProcessing;
};

export type MeetingProcessing = {
  readonly transcript: "pending" | "partial" | "complete" | "failed";
  readonly notes: "pending" | "partial" | "complete" | "failed";
  readonly memory: "pending" | "partial" | "complete" | "failed";
  readonly recording: "pending" | "partial" | "complete" | "failed";
};

export type GetMeetingInput = {
  readonly meeting_id: string;
};

export type GetTranscriptInput = {
  readonly meeting_id: string;
  readonly cursor?: string;
  readonly limit?: number;
};

export type GetTranscriptOutput = {
  readonly items: ReadonlyArray<TranscriptSegment>;
  readonly next_cursor: string | null;
};

export type TranscriptSegment = {
  readonly id: string;
  readonly source: SourceRange;
  readonly text: string;
  readonly status: "partial" | "final";
  readonly revision: number;
  readonly origin: "live" | "batch" | "correction";
  readonly provider: string;
  readonly model: string;
  readonly provider_connection_id: string | null;
  readonly speaker_label: string | null;
  readonly speaker_track_id: string | null;
  readonly confidence: number | null;
  readonly created_at: string;
};

export type SourceRange = {
  readonly epoch_id: string;
  readonly track: number;
  readonly sample_start: number;
  readonly sample_end: number;
};

export type RecordingAccessInput = {
  readonly meeting_id: string;
};

export type RecordingAccess = {
  readonly meeting_id: string;
  readonly boundary_revision: number;
  readonly url: string;
  readonly expires_at: string;
  readonly gaps: ReadonlyArray<SourceRange>;
};

export type GetContextInput = {
  readonly meeting_id: string;
};

export type ContextSnapshot = {
  readonly meeting_id: string;
  readonly revision: number;
  readonly as_of: string;
  readonly timezone: string;
  readonly source_watermark: ContextSnapshotSourceWatermark | null;
  readonly items: ReadonlyArray<ContextItem>;
  readonly changes_cursor: string;
  readonly truncated: boolean;
};

export type ContextSnapshotSourceWatermark = {
  readonly epoch_id: string;
  readonly sample_end: number;
};

export type ContextItem = {
  readonly id: string;
  readonly revision: number;
  readonly meeting_id: string | null;
  readonly kind: "decision" | "commitment" | "constraint" | "project_fact" | "preference" | "open_question" | "research_observation";
  readonly text: string;
  readonly state: "provisional" | "committed" | "superseded";
  readonly derivation: "spoken" | "inferred" | "human_correction" | "external";
  readonly event_at: string | null;
  readonly valid_from: string | null;
  readonly valid_until: string | null;
  readonly time: TimeExpression | null;
  readonly author: Author;
  readonly sources: ReadonlyArray<SegmentSource | ArtifactSource>;
  readonly supersedes: ContextItemSupersedes | null;
  readonly created_at: string;
};

export type TimeExpression = {
  readonly phrase: string;
  readonly normalized: string | null;
  readonly anchor: string;
  readonly timezone: string;
  readonly ambiguous: boolean;
};

export type Author = {
  readonly type: "human" | "agent" | "system";
  readonly id: string;
};

export type SegmentSource = {
  readonly segment_id: string;
  readonly start_ms: number;
  readonly end_ms: number;
};

export type ArtifactSource = {
  readonly artifact_id: string;
};

export type ContextItemSupersedes = {
  readonly id: string;
  readonly revision: number;
};

export type SearchContextInput = {
  readonly q: string;
  readonly meeting_id?: string;
  readonly cursor?: string;
  readonly limit?: number;
};

export type SearchContextOutput = {
  readonly items: ReadonlyArray<ContextItem>;
  readonly next_cursor: string | null;
};

export type AddContextItem = {
  readonly meeting_id: string | null;
  readonly expected_revision: number;
  readonly kind: "decision" | "commitment" | "constraint" | "project_fact" | "preference" | "open_question" | "research_observation";
  readonly text: string;
  readonly sources: ReadonlyArray<SegmentSource | ArtifactSource>;
  readonly idempotency_key: string;
};

export type ReviseContextItemInput = {
  readonly expected_revision: number;
  readonly text: string;
  readonly sources: ReadonlyArray<SegmentSource | ArtifactSource>;
  readonly idempotency_key: string;
  readonly item_id: string;
};

export type GetContextChangesInput = {
  readonly meeting_id?: string;
  readonly cursor?: string;
  readonly limit?: number;
};

export type GetContextChangesOutput = {
  readonly items: ReadonlyArray<ContextEvent>;
  readonly next_cursor: string | null;
};

export type ContextEvent = {
  readonly seq: number;
  readonly meeting_id: string | null;
  readonly item: ContextEventItem | null;
  readonly change: "item_added" | "item_revised" | "item_superseded" | "meeting_boundary_changed" | "access_changed";
  readonly actor: string;
  readonly permission_revision: number;
  readonly created_at: string;
};

export type ContextEventItem = {
  readonly id: string;
  readonly revision: number;
};

export type GetSourceInput = {
  readonly source_id: string;
};

export type SourceRecord = {
  readonly id: string;
  readonly kind: "segment" | "artifact";
  readonly meeting_id: string | null;
  readonly text: string;
  readonly segment: TranscriptSegment | null;
};

export type SearchIntegrationActionsInput = {
  readonly intent: string;
  readonly app?: string;
  readonly limit?: number;
};

export type SearchIntegrationActionsOutput = {
  readonly matches: ReadonlyArray<IntegrationActionMatch>;
  readonly refinement_hint: string | null;
};

export type IntegrationActionMatch = {
  readonly action_key: string;
  readonly app: string;
  readonly purpose: string;
  readonly connection: "connected" | "not_connected" | "not_permitted";
  readonly effect: "read" | "write" | "send" | "delete";
};

export type GetIntegrationActionInput = {
  readonly account_id?: string;
  readonly configuration?: Readonly<Record<string, unknown>>;
  readonly field?: string;
  readonly options_cursor?: string;
  readonly action_key: string;
};

export type GetIntegrationActionOutput = {
  readonly action_key: string;
  readonly version: string;
  readonly configuration_ref: string;
  readonly fields: ReadonlyArray<GetIntegrationActionOutputFieldsItem>;
  readonly missing: ReadonlyArray<string>;
  readonly options: GetIntegrationActionOutputOptions | null;
  readonly complete: boolean;
};

export type GetIntegrationActionOutputFieldsItem = {
  readonly name: string;
  readonly type: string;
  readonly required: boolean;
  readonly description: string | null;
  readonly remote_options: boolean;
};

export type GetIntegrationActionOutputOptions = {
  readonly field: string;
  readonly values: ReadonlyArray<GetIntegrationActionOutputOptionsValuesItem>;
  readonly next_cursor: string | null;
};

export type GetIntegrationActionOutputOptionsValuesItem = {
  readonly label: string;
  readonly value: unknown;
};

export type RequestActionInput = {
  readonly action_key: string;
  readonly configuration_ref: string;
  readonly version: string;
  readonly arguments: Readonly<Record<string, unknown>>;
  readonly meeting_id: string | null;
  readonly idempotency_key: string;
};

export type RequestActionOutput = {
  readonly action_id: string;
  readonly state: "proposed" | "awaiting_authorization" | "queued" | "running" | "succeeded" | "failed" | "unknown" | "cancelled";
};

export type GetActionInput = {
  readonly action_id: string;
};

export type ActionReceipt = {
  readonly action_id: string;
  readonly action_key: string;
  readonly meeting_id: string | null;
  readonly state: "proposed" | "awaiting_authorization" | "queued" | "running" | "succeeded" | "failed" | "unknown" | "cancelled";
  readonly args_sha256: string;
  readonly grant: ActionReceiptGrant | null;
  readonly provider_receipt: Readonly<Record<string, unknown>> | null;
  readonly attempts: number;
  readonly reconciliation: "none" | "pending" | "reconciled";
  readonly updated_at: string;
};

export type ActionReceiptGrant = {
  readonly id: string;
  readonly version: number;
};

export type ListAgentsInput = {
  readonly cursor?: string;
  readonly limit?: number;
};

export type ListAgentsOutput = {
  readonly items: ReadonlyArray<AgentCredential>;
  readonly next_cursor: string | null;
};

export type AgentCredential = {
  readonly credential_id: string;
  readonly agent_id: string;
  readonly display_name: string;
  readonly scopes: ReadonlyArray<"context:read" | "context:write" | "recordings:read" | "actions:request" | "actions:execute" | "workspace:admin" | "capture:ingest">;
  readonly meeting_ids: ReadonlyArray<string> | null;
  readonly created_at: string;
  readonly expires_at: string | null;
  readonly revoked_at: string | null;
  readonly last_used_at: string | null;
};

export type CreateAgent = {
  readonly display_name: string;
  readonly scopes: ReadonlyArray<"context:read" | "context:write" | "recordings:read" | "actions:request" | "actions:execute" | "workspace:admin" | "capture:ingest">;
  readonly meeting_ids: ReadonlyArray<string> | null;
  readonly expires_at: string | null;
};

export type CreateAgentOutput = {
  readonly credential: AgentCredential;
  readonly token: string;
};

export type RevokeCredentialInput = {
  readonly agent_id: string;
  readonly credential_id: string;
};

export interface Operations {
  'health.healthz': { input: Readonly<Record<string, unknown>>; output: HealthzOutput };
  'health.readyz': { input: Readonly<Record<string, unknown>>; output: ReadyzOutput };
  'session.getSession': { input: Readonly<Record<string, unknown>>; output: AccessScope };
  'meetings.listMeetings': { input: ListMeetingsInput; output: ListMeetingsOutput };
  'meetings.getMeeting': { input: GetMeetingInput; output: Meeting };
  'meetings.getTranscript': { input: GetTranscriptInput; output: GetTranscriptOutput };
  'meetings.recordingAccess': { input: RecordingAccessInput; output: RecordingAccess };
  'context.getContext': { input: GetContextInput; output: ContextSnapshot };
  'context.searchContext': { input: SearchContextInput; output: SearchContextOutput };
  'context.addContextItem': { input: AddContextItem; output: ContextItem };
  'context.reviseContextItem': { input: ReviseContextItemInput; output: ContextItem };
  'context.getContextChanges': { input: GetContextChangesInput; output: GetContextChangesOutput };
  'context.getSource': { input: GetSourceInput; output: SourceRecord };
  'integrations.searchIntegrationActions': { input: SearchIntegrationActionsInput; output: SearchIntegrationActionsOutput };
  'integrations.getIntegrationAction': { input: GetIntegrationActionInput; output: GetIntegrationActionOutput };
  'actions.requestAction': { input: RequestActionInput; output: RequestActionOutput };
  'actions.getAction': { input: GetActionInput; output: ActionReceipt };
  'agents.listAgents': { input: ListAgentsInput; output: ListAgentsOutput };
  'agents.createAgent': { input: CreateAgent; output: CreateAgentOutput };
  'agents.revokeCredential': { input: RevokeCredentialInput; output: AgentCredential };
}

export const operations: Record<keyof Operations, OperationSpec> = {
  'health.healthz': {"method":"GET","path":"/healthz","pathParams":[],"queryParams":[],"body":false},
  'health.readyz': {"method":"GET","path":"/readyz","pathParams":[],"queryParams":[],"body":false},
  'session.getSession': {"method":"GET","path":"/api/v1/session","pathParams":[],"queryParams":[],"body":false},
  'meetings.listMeetings': {"method":"GET","path":"/api/v1/meetings","pathParams":[],"queryParams":["state","cursor","limit"],"body":false},
  'meetings.getMeeting': {"method":"GET","path":"/api/v1/meetings/{meeting_id}","pathParams":["meeting_id"],"queryParams":[],"body":false},
  'meetings.getTranscript': {"method":"GET","path":"/api/v1/meetings/{meeting_id}/transcript","pathParams":["meeting_id"],"queryParams":["cursor","limit"],"body":false},
  'meetings.recordingAccess': {"method":"POST","path":"/api/v1/meetings/{meeting_id}/recording-access","pathParams":["meeting_id"],"queryParams":[],"body":false},
  'context.getContext': {"method":"GET","path":"/api/v1/meetings/{meeting_id}/context","pathParams":["meeting_id"],"queryParams":[],"body":false},
  'context.searchContext': {"method":"GET","path":"/api/v1/context/search","pathParams":[],"queryParams":["q","meeting_id","cursor","limit"],"body":false},
  'context.addContextItem': {"method":"POST","path":"/api/v1/context/items","pathParams":[],"queryParams":[],"body":true},
  'context.reviseContextItem': {"method":"PATCH","path":"/api/v1/context/items/{item_id}","pathParams":["item_id"],"queryParams":[],"body":true},
  'context.getContextChanges': {"method":"GET","path":"/api/v1/context/changes","pathParams":[],"queryParams":["meeting_id","cursor","limit"],"body":false},
  'context.getSource': {"method":"GET","path":"/api/v1/sources/{source_id}","pathParams":["source_id"],"queryParams":[],"body":false},
  'integrations.searchIntegrationActions': {"method":"GET","path":"/api/v1/integrations/actions","pathParams":[],"queryParams":["intent","app","limit"],"body":false},
  'integrations.getIntegrationAction': {"method":"POST","path":"/api/v1/integrations/actions/{action_key}/schema","pathParams":["action_key"],"queryParams":[],"body":true},
  'actions.requestAction': {"method":"POST","path":"/api/v1/actions","pathParams":[],"queryParams":[],"body":true},
  'actions.getAction': {"method":"GET","path":"/api/v1/actions/{action_id}","pathParams":["action_id"],"queryParams":[],"body":false},
  'agents.listAgents': {"method":"GET","path":"/api/v1/agents","pathParams":[],"queryParams":["cursor","limit"],"body":false},
  'agents.createAgent': {"method":"POST","path":"/api/v1/agents","pathParams":[],"queryParams":[],"body":true},
  'agents.revokeCredential': {"method":"DELETE","path":"/api/v1/agents/{agent_id}/credentials/{credential_id}","pathParams":["agent_id","credential_id"],"queryParams":[],"body":false},
};
