-- Better Auth organization plugin for the embedded issuer (server/src/issuer.ts): organizations,
-- members and invitations, plus the session's active organization. Generated by better-auth 1.7.7
-- `getMigrations(...).compileMigrations()` against a database with every other migration applied, using createIssuer's
-- options, then reviewed; one object per statement. Additive only. Better Auth owns these rows;
-- issuer-orgs.ts mirrors them into workspace_members. Empty and unused while SANCTUM_EMBEDDED_ISSUER is unset.

alter table `auth_session` add column `activeOrganizationId` text;
create table `auth_organization` (`id` varchar(36) not null primary key, `name` varchar(255) not null, `slug` varchar(255) not null unique, `logo` text, `createdAt` timestamp(3) not null, `metadata` text);
create table `auth_member` (`id` varchar(36) not null primary key, `organizationId` varchar(36) not null references `auth_organization` (`id`) on delete cascade, `userId` varchar(36) not null references `auth_user` (`id`) on delete cascade, `role` varchar(255) not null, `createdAt` timestamp(3) not null);
create table `auth_invitation` (`id` varchar(36) not null primary key, `organizationId` varchar(36) not null references `auth_organization` (`id`) on delete cascade, `email` varchar(255) not null, `role` varchar(255), `status` varchar(255) not null, `expiresAt` timestamp(3) not null, `createdAt` timestamp(3) default CURRENT_TIMESTAMP(3) not null, `inviterId` varchar(36) not null references `auth_user` (`id`) on delete cascade);
create index `auth_member_organizationId_idx` on `auth_member` (`organizationId`);
create index `auth_member_userId_idx` on `auth_member` (`userId`);
create index `auth_invitation_organizationId_idx` on `auth_invitation` (`organizationId`);
create index `auth_invitation_email_idx` on `auth_invitation` (`email`);
